site_name: "Experimental representation of vrsatile in LinkML"
theme:
  name: readthedocs
  features:
    - content.tabs.link
plugins:
  - search
nav:
  - Index: index.md
  - About: about.md
site_url: https://biodatamodels.github.io/vrsatile/
repo_url: https://github.com/biodatamodels/vrsatile/
